### ISSUE TITLE
Issue on Windows

### ISSUE THREAD

**Issue by fartbagxp** [TheSharks/WildBeast#144]
I got the bot up and running using the installation to Windows guide.
FortuneCow works, but the youtube music part is failing.

The error message, which doesn't tell me much.
`AssignProcessToJobObject(87) and parameter is incorrect`

Request:
!request https://youtube.com/(link)

- The bot enters, exit the voice channel just fine.
- I have generated the google key multiple times, and still has issues.
- This is running on node v6.7.0, which is latest as of today.

**Comment by SteamingMutt** [comment]
`AssignProcessToJobObject(87)` is a C# function, try installing the [C++ Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools) and try again.
Another thing you can try is opening the command prompt as Administrator.

**Comment by fartbagxp** [comment]
Seems to be working. Thanks.
