### ISSUE TITLE
Username change

### ISSUE THREAD

**Issue by Mirrorbreak** [TheSharks/WildBeast#146]
Add a command that changes the bot's username.

**Comment by SteamingMutt** [comment]
`++eval bot.User.setUsername('ayy lmao')`
:shipit:

**Comment by Mirrorbreak** [comment]
LW told me to, gosh, sorry

**Comment by LWTechGaming** [comment]
😂 well, it was an idea.

**Comment by SteamingMutt** [comment]
We're not BorkedBot with 10 thousand shortcuts for everything.
