### ISSUE TITLE
Update FFmpeg

### ISSUE THREAD

**Issue by SteamingMutt** [TheSharks/WildBeast#149]
This one is easy, replace the FFmpeg executables in the repo with the latest version.

**Comment by madan96** [comment]
I would like to do this one.

**Comment by SteamingMutt** [comment]
.exe files can be found on [Zeranoe](https://ffmpeg.zeranoe.com/builds/), get a static build.
The mac versions can be found on [here](http://www.ffmpegmac.net/).

**Comment by jonny2plates** [comment]
32 bit or 64 for windows?

**Comment by thenightex** [comment]
32
