### ISSUE TITLE
 Unexpected token M in JSON at position 48

### ISSUE THREAD

**Issue by MrWhoHasNoName** [TheSharks/WildBeast#157]
I have done everything as n the guide, but when I run the test is says: "WildBeast encountered an error while trying to load the config file, please resolve this issue and restart WildBeast", and " Unexpected token M in JSON at position 48", but there isnt even a 48 .
Pls help

**Comment by LWTechGaming** [comment]
Check your file using http://jsonlint.com and fix the violation if you can.

If required, join our Discord server at https://discord.gg/0cFoiR5QVh5LZlQO and we'll help you further.

**Comment by MrWhoHasNoName** [comment]
Does the token need to be in brackes or anything like that?

**Comment by LWTechGaming** [comment]
Looks like you're missing a quote. Most likely your token line.
Make sure your token is formatted like this:
```json
"token": "bot token",
```
Ensure that none of that is missing, save the file and try again.

**Comment by MrWhoHasNoName** [comment]
Ok, now it seems to be fixen, now I get another error on the permissions part.  The JSONlint says this: Error: Parse error on line 17:
...0049107577012224]		"level1": [],		"lev
----------------------^

So I think there is something wrong in the user ID part

**Comment by MrWhoHasNoName** [comment]
Ayyy nvm, fixed it
Than you for your help

**Comment by LWTechGaming** [comment]
Ah, no problem :)
