### ISSUE TITLE
Google Projects API documentation is out of date

### ISSUE THREAD

**Issue by CaymonS** [TheSharks/WildBeast#159]
Google updated the process of acquiring a API key for YouTube Data, and is looks completely different than is does on the Wiki

^_^b

On another note, what about putting the Wiki in the git so outsiders can do pulls on the Wiki. *cough cough* so I could make the update myself *cough cough*

**Comment by SteamingMutt** [comment]
https://github.com/TheSharks/WildBeast.wiki.git
👀

**Comment by LWTechGaming** [comment]
Thanks for reporting that, I'll be updating it ASAP.

About your request on the wiki being editable for outsiders, I think we manage documentation pretty well internally. I mean, how can we be sure of that you know what you're talking about on first sight? We can't, really. Therefore we have restricted documentation modification to @TheSharks/wiki-team.

**Comment by LWTechGaming** [comment]
*Also...*
404 not found. Good job @SteamingMutt.

**Comment by SteamingMutt** [comment]
@LWTechGaming It's a valid git clone link you scrubbo, it's not a *repository*.

**Comment by LWTechGaming** [comment]
Ahh, didn't note that one kek

**Comment by LWTechGaming** [comment]
@CaymonS Now that wasn't rocket science, was it? It just takes you to a different page in the initial creation process deeming from when I just went through the process again 😂
