### ISSUE TITLE
[Experimental] Make RethinkDB Start when DougBot.js is started

### ISSUE THREAD

**Issue by Miwrzezl** [TheSharks/WildBeast#163]
this can make less confusion between new people doing this sort of thing, also considering RethinkDB Linux & Windows has the same command if in path 👀

**Comment by LWTechGaming** [comment]
Maybe, but one request: Please don't make 1 hour of writing work inert, thank you. Not in the mood right now.

**Comment by SteamingMutt** [comment]
Rethink *could* be started with DougBot, but this presents problems with memory/CPU, as rethink is designed to be run as a parent, not as a child process.
