### ISSUE TITLE
Bind bot to single channel during voice, fix deanpower along with that.

### ISSUE THREAD

**Issue by zaza7** [TheSharks/WildBeast#174]
The bot should only listen for music commands in the channel it was initiated on so that others can't use commands like request or skip without being in the same channel as the was started on.

**Comment by zaza7** [comment]
Partially closed, deanpower has been resolved by commit d3c3c20, the bot is not yet binding to a single channel.

**Comment by LWTechGaming** [comment]
I think you might want to make the bot only take requests from people that are in VC when the bot is playing moozic.

**Comment by zaza7** [comment]
Soooo bind to channel where it was initialized to keep cross channel spam down and only from those in voice to keep trolls out? but they could just join, request, leave besides it already requiring level 1 IIRC

**Comment by SteamingMutt** [comment]
*Why not both*

**Comment by zaza7** [comment]
![image](https://cloud.githubusercontent.com/assets/4474031/20276558/be0dbe00-aa6a-11e6-818b-6b00e87248a0.jpg)

**Comment by zaza7** [comment]
Voice needs to be rewritten from scratch therefore this issue will be closed.
