### ISSUE TITLE
Global voice slot limit instead of per-shard

### ISSUE THREAD

**Issue by arunesh90** [TheSharks/WildBeast#177]

**Comment by arunesh90** [comment]
rip I can't add labels
![image](https://cloud.githubusercontent.com/assets/5787588/20407027/eb565dc0-ad0f-11e6-9a56-cc048085f8d5.png)

**Comment by arunesh90** [comment]
wew

**Comment by zaza7** [comment]
Must be really?

**Comment by arunesh90** [comment]
well if you really want to utilize everything you have, yes.
For example someone just asked what the all slots taken msg meant, while just 65% was being used at the moment, the cpu that was left could've been used to stream agario content to his voice channel.

**Comment by Nenkai** [comment]
TL;DR - Streaming slots should be limited globally rather than shard limited so it doesn't actually all streaming slots are used, while it is actually the shard's

That does not improve performace though, since that resumes uses all the slots the bot has.

**Comment by zaza7** [comment]
And the process runs on a single CPU thread which is why we run a per shard limit and multiple shards cause ya know node.js is not multi-threaded

**Comment by zaza7** [comment]
Also the dedi is already at like 95-98% usage

**Comment by zaza7** [comment]
@SteamingMutt So are we ever going to switch from a per shard limit to global? It's not impossible to do just remember, the process is single threaded so too many connections in one process will degrade performance for all guilds using that shard.

**Comment by Dougley** [comment]
We no longer have a voice slot limitation, closing.
