### ISSUE TITLE
Delete Guild Database, on leave-server (or bot kick, whatevs..)

### ISSUE THREAD

**Issue by Nenkai** [TheSharks/WildBeast#178]
^ To save storage space, no point keeping the database if the a bot leaves a guild.

(Also ownership transfer isn't logged, re-adding the bot to reset the guild data could be a temporary fix.)

**Comment by zaza7** [comment]
We are already planning on making sure the bot will update the database should the server owner change, I thought the DB was deleted on leave unless we lost that ability in the change to rDB, I guess we can run a script to check all servers and update accordingly if the owner in the DB does not match the server owner.
