### ISSUE TITLE
Youtube API not working?

### ISSUE THREAD

**Issue by DrXala** [TheSharks/WildBeast#180]
We have youtube-dl and ytbe-dl in dependencies with youtube-api. I have set youtube API key in my `config.json` but I have no stats in my google dashboard.

Does the youtube stream do not work via API in this version?

**Comment by Nenkai** [comment]
You won't get any data if you're requesting simple vids.

Youtube Data API provides data to handles youtube playlists. youtube-dl is unrelated.

**Comment by DrXala** [comment]
Ok, thank you for this clarification.
