### ISSUE TITLE
Improve Logging

### ISSUE THREAD

**Issue by RyoshiKayo** [TheSharks/WildBeast#206]
Yes improve logging ffs

Specifically 

> the value of the _trace in the hello or ready
> and an exact timestamp
-Jake

**Comment by RyoshiKayo** [comment]
`_trace`, `hello` or `ready` from the JSON reply from the Discord Gateway

**Comment by SteamingMutt** [comment]
Logging will be improved in next minor release.

Soon™

**Comment by RyoshiKayo** [comment]
@SteamingMutt Add Shard ID in pm2 logs

**Comment by SteamingMutt** [comment]
Finished as of 4.2.0
