### ISSUE TITLE
Docker : Database missing

### ISSUE THREAD

**Issue by BleuDiamant** [TheSharks/WildBeast#214]
![06783973](https://cloud.githubusercontent.com/assets/8930930/21982370/46265efc-dbec-11e6-8a47-a44e1b056329.png)
I have install the bot directly from docker beacause manual installation doesn't work, now the bot launch correctly but the database is missing all setting is not changed
Thank :)

**Comment by LWTechGaming** [comment]
Did you start wildbeast-rethink before you started WildBeast like the guide instructed?

**Comment by BleuDiamant** [comment]
ok is my fault 
i don't have this container
i have retry manual installation but a have this error
![91185830](https://cloud.githubusercontent.com/assets/8930930/21983290/cdd06330-dbf0-11e6-87f3-801887ecd130.png)

**Comment by BleuDiamant** [comment]
Okay i have found the problem my shell doesn't know how connect to the docker daemon to avoid this i have launch docker cli direclty trough
Now i have two container i have launch rethink at first and after wildbeast.
but when a type "help" on my server i have this error
warn: Database file missing for a server, creating one now...
error:  ReqlOpFailedError: Database `Discord` does not exist in:

```
r.db("Discord").table("Guilds").insert({
^^^^^^^^^^^^^^^                         
    customize: {
        nsfw: null,
        perms: null,
        prefix: null,
        timeout: null,
        welcome: false,
        welcomeMessage: null
    },
    id: "********************",
    lang: "en",
    perms: {
        roles: {
            level1: [],
            level2: [],
            level3: [],
            negative: []
        },
        standard: {
            everyone: 0,
            level1: [],
            level2: [],
            level3: [],
            negative: []
        },
        nsfw: []
    },
    superUser: "********************"
})
2017-01-16T19:21:43.099694221Z 
    at Connection._processResponse (/usr/src/WildBeast/node_modules/rethinkdbdash/lib/connection.js:395:15)
    at Socket.<anonymous> (/usr/src/WildBeast/node_modules/rethinkdbdash/lib/connection.js:201:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
```

**Comment by LWTechGaming** [comment]
@SteamingMutt @zaza7 `npm run-script createdatabase` is a thing right?

**Comment by SteamingMutt** [comment]
`npm run-script dbcreate`

Op 16 jan. 2017 om 20:32 heeft Linus Willner <notifications@github.com> het
volgende geschreven:

@SteamingMutt <https://github.com/SteamingMutt> @zaza7
<https://github.com/zaza7> npm run-script createdatabase is a thing right?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/TheSharks/WildBeast/issues/214#issuecomment-272945215>,
or mute the thread

**Comment by LWTechGaming** [comment]
Well... Whatever.

**Comment by Nenkai** [comment]
Resolved on the discord server, closing issue
