### ISSUE TITLE
Command cooldown message will be returned regardless of negative permission level

### ISSUE THREAD

**Issue by Nenkai** [TheSharks/WildBeast#216]
![Test](http://i.imgur.com/XRq67n5.png)

**Comment by SteamingMutt** [comment]
Known issue, due to the way we check for timeouts *first* before we check for permissions we always fire a timeout.

**Comment by zaza7** [comment]
👌 Check for permissions first then timeout, this can be done.

**Comment by zaza7** [comment]
This should now be fixed in the latest commit to experimental.
