### ISSUE TITLE
Cleverbot broken

### ISSUE THREAD

**Issue by d0p1s4m4** [TheSharks/WildBeast#239]
cleverbot "api" change. It was fixed in cleverbot-node 0.2.7. 
In packages.json ```"cleverbot-node": "^0.2.6"``` need to be ```"cleverbot-node": "^0.2.7"```

**Comment by SteamingMutt** [comment]
~~Free pr~~
Our current version range should cover that, run `npm update`

**Comment by Nenkai** [comment]
Fixed in last cleverbot-node update, closing
