### ISSUE TITLE
Request: !prune only one person's messages

### ISSUE THREAD

**Issue by natsuo** [TheSharks/WildBeast#246]
Nyan nyan.

Is it possible to add another parameter to the !prune command to specify a certain person's messages should be removed?

`!prune 3` should remove 3 messages.
`!prune 3 @Kea` should remove 3 of @Kea's messages, but not touch the other people's.

Aaaand while I'm at it. Should the number-parameter be inclusive or exclusive? I mean, to me, it makes more sense that the command removes three actual messages/lines, and not just two lines and the !prune line. The !prune command in my opinion should be removed and not affect the overall number of lines being removed.

**Comment by caf203** [comment]
Done on V6, syntax goes as follows:
`purge/clean author @person 1-100`
