### ISSUE TITLE
Selfhosting: Allow toggling of leaving voice after playlist finish

### ISSUE THREAD

**Issue by LWTechGaming** [TheSharks/WildBeast#253]
Many selfhosters often want this option disabled. Hence they should be allowed to do that without having to modify the code by themselves. My suggestion would be this being true by default in the config.

The change is not groundbreaking as it doesn't affect our official instance. The edits are also fairly minor as they only need to take into account the new config variable. I'll be looking into doing this ASAP.

**Comment by zaza7** [comment]
remember how i said voice needed a rewrite? this is in the plans but as you know current progress is slow for reasons.

**Comment by LWTechGaming** [comment]
I guess this is a good point to start at then? 😉

**Comment by zaza7** [comment]
maybe you should start the rewrite then :D

**Comment by thewillwilson** [comment]
How does one go about this until the update is done?

**Comment by LWTechGaming** [comment]
By tweaking `~/runtime/internal/voice.js`. If you know programming and Discord bots you should be able to find it fairly easily.
