### ISSUE TITLE
Problem with "npm run-script dbcreate"

### ISSUE THREAD

**Issue by Lop-Sided** [TheSharks/WildBeast#254]
Hi,

I'm having an issue running the bot / setting up database. I'm pretty sure I've followed everything in the guide correctly.

node.js is installed (node -v returns "v6.9.4")
rethinkdb is installed ("rethinkdb --daemon" doesn't return any errors, and seems to be running)

When it comes to using "npm run-script dbcreate" I'm getting the following errors:

![image](https://cloud.githubusercontent.com/assets/12783270/24307742/3acaf4b8-10bd-11e7-99b9-c77429bdd3ee.png)

Any help/advice appreciated, no doubt I've missed out a crucial step! Thanks

**Comment by SteamingMutt** [comment]
`cd WildBeast`

**Comment by wdraz** [comment]
Great, thanks. Seems to get rid of the errors. However it's now coming back with the following:

![image](https://cloud.githubusercontent.com/assets/12783270/24307899/dbbe67ec-10bd-11e7-90e1-85e2ba0a9975.png)

Which is weird, because it seems as though rethinkdb is running.

![image](https://cloud.githubusercontent.com/assets/12783270/24307954/045e447e-10be-11e7-84e9-c1a8c3a2d6cb.png)

**Comment by SteamingMutt** [comment]
`killall rethinkdb && rethinkdb --deamon --bind 127.0.0.1`

**Comment by wdraz** [comment]
Still no luck, returning same 'could not connect to the RethinkDB instance'

![image](https://cloud.githubusercontent.com/assets/12783270/24312342/06d9a524-10d0-11e7-9b65-a1b803215f97.png)

what can I do to troubleshoot the problem with RethinkDB?

**Comment by SteamingMutt** [comment]
Is your database configuration in your config file correct, if you configured a password you need to enter that into the config file too, for example.

**Comment by wdraz** [comment]
I didn't create any password when installing RethinkDB, so I've left everything as default.

`  "database": {
    "host": "localhost",
    "port": 29015,
    "password": "",
    "user": "admin"
  },`

Is there a way to check these credentials are correct, or reset them just in-case?

**Comment by TheMrRoboto** [comment]
Do you have anything running on port 8080?

**Comment by LWTechGaming** [comment]
Nothing has happened here in a month. Closing this.
