### ISSUE TITLE
Help DM does not send when the message exceeds the character limit due to custom commands.

### ISSUE THREAD

**Issue by Nenkai** [TheSharks/WildBeast#276]
I thought the help was already by default splitted to multiple messages by default, guess not.

**Comment by LWTechGaming** [comment]
This has thus far not been necessary as our command list has not been expounded beyond 2000 characters. I'll look to fix this later.

**Comment by SteamingMutt** [comment]
This has already been fixed in https://github.com/TheSharks/WildBeast/commit/da8ee8062576152a93152f33e3609fa8622bf17b
