### ISSUE TITLE
[request] Message delete

### ISSUE THREAD

**Issue by Tslimshady99** [TheSharks/WildBeast#277]
A message delete system, that servers can toggle on or off, that the bot will remove or not remove a users message once a command is issued.

**Comment by LWTechGaming** [comment]
If I understood correctly, this is bad practice for command transparency. Then you won't know who issued the command and users may misunderstand that the bot is malfunctioning, which may lead to unfortunate disagreements.

If you believe I didn't correctly, you can elaborate on the thought. If not, I'll be closing this issue soon.

**Comment by Tslimshady99** [comment]
I was just think it would be a good feature so that if a lot of people are using the bot then, to keep chats clean, the server owner can toggle something, that could delete the users message after like 10 to 20 sec or something, and same with the bot, but if you fell it wouldn’t be the you can close it

**Comment by LWTechGaming** [comment]
We have the bot automatically deleting messages related to for instance music because those are very frequent. Though that only deletes the bot's message and not the user's, for transparency reasons.
