### ISSUE TITLE
Custom commands break help

### ISSUE THREAD

**Issue by JamiePhonic** [TheSharks/WildBeast#280]
I've discovered that adding in any custom commands appears to break the output of the "{Prefix}help" command.
This includes the example custom commands in the docs.

I'm currently running WildBeast 4.3.0 on Windows server 2012, with node V6.11.1

[help.png](https://postimg.org/image/i2s96ec8j/)

**Comment by SteamingMutt** [comment]
We have a fix for this already in master. (freshly merged, actually) https://github.com/TheSharks/WildBeast/commit/8fbe08f2af30aeec8335fe748741955bda8d611d

**Comment by JamiePhonic** [comment]
Ha! 
It must have been merged literally just as i submitted this!
I can confirm that it is now fixed though, so ill close this.
