### ISSUE TITLE
Add a <prefix>oof command.

### ISSUE THREAD

**Issue by DefaultG** [TheSharks/WildBeast#282]
An oof or uff command that would play the Roblox death sound or the Minecraft 'uff' sounds with respective commands in randomly varying pitches. I think this is something every Discord bot needs, especially if it is somewhat meme oriented, lol.

**Comment by caf203** [comment]
WildBot isn't a soundboard, checkout [Yggdrasil](https://bots.discord.pw/bots/247283454440374274) if you want one.

**Comment by DefaultG** [comment]
Oh, okay. Thanks man!
