### ISSUE TITLE
Request: How to set a Game to the bot ?

### ISSUE THREAD

**Issue by ufdxN** [TheSharks/WildBeast#289]
All in the title, please help me ._.

**Comment by Tslimshady99** [comment]
If you replace the current setstatus with this in it will work, 
`Commands.setstatus = {
  name: 'setstatus',
  help: 'Change my playing status on Discord to something else or pass nothing to clear the status!',
  usage: '<online / idle / dnd / invisible / twitch url> [playing stats]',
  level: 'master',
  fn: function (msg, suffix, bot) {
    var first = suffix.split(' ')
    if (!suffix) {
      bot.User.setStatus('online', null)
      msg.channel.sendMessage(`Cleared status.`)
    } else {
      if (/^https?/.test(first[0])) {
        bot.User.setStatus(null, {
          type: 1,
          name: (first[1] ? suffix.substring(first[0].length + 1) : null),
          url: first[0]
        })
        msg.channel.sendMessage(`Set status to streaming with message ${suffix.substring(first[0].length + 1)}`)
      } else if (['online', 'idle', 'dnd', 'invisible'].indexOf(first[0]) > -1) {
        bot.User.setStatus(first[0], {
          type: 0,
          name: (first[1] ? suffix.substring(first[0].length + 1) : null)
        })
        msg.channel.sendMessage(`Set status to ${first[0]} with message ${suffix.substring(first[0].length + 1)}`)
      } else if (suffix.substring(first[0].length + 1).length < 1) {
        msg.reply(':warning: Can only be `online`, `idle`, `dnd` or `invisible`!')
      } else {
        bot.User.setStatus('online', null)
        msg.channel.sendMessage(`Cleared status.`)
      }
    }
  }
}`

**Comment by caf203** [comment]
You don't need to provide type if you do `npm update qeled/discordie#dev`, as #q already updated the lib to accommodate for the type change.
