### ISSUE TITLE
Rule34 Links Broken.

### ISSUE THREAD

**Issue by NickGurMatic69** [TheSharks/WildBeast#293]
Wildbot posts them with an extra http: which breaks the hyperlinking. https://i.imgur.com/FdQJRBd.png

**Comment by Nenkai** [comment]
Known issue, can you confirm if it only happens for `webm`'s?

**Comment by NickGurMatic69** [comment]
It happens with every format I've tried, and since webm's can't be previewed, only png, gif, jpeg, etc still preview without being hyperlinked. https://i.imgur.com/WeoQ01e.png

**Comment by SteamingMutt** [comment]
Fixed in https://github.com/TheSharks/WildBeast/commit/ee074067af15de2dc39d6e1b993bdeed228d7c26, should be live on WildBot in a few.
