### ISSUE TITLE
Welcome message doesn't seem to work

### ISSUE THREAD

**Issue by TLNiles** [TheSharks/WildBeast#304]
customize welcoming is set to `channel`
customize welcome was custom, written at some point on russian (so I though that reason would be cyrilic letters), and then on english.
Bot gives this error whenever someone joins the server:

```
error:  TypeError: Cannot read property 'sendMessage' of null
    at datacontrol.customize.reply.then (D:\WildBeast bot\WildBeast\DougBot.js:2
64:34)
    at <anonymous>
```

**Comment by Dougley** [comment]
This is a problem related to a breaking API change, it's been fixed in the experimental branch since https://github.com/TheSharks/WildBeast/commit/9b445ac97ececac3f50ba6ed024317a1ffee6d22.
This commit will introduce a new customize method to set the welcoming channel separately.

**Comment by TLNiles** [comment]
Should I try and update to experimental branch, or there will be new stable release soon with this fix included?

**Comment by Dougley** [comment]
Update to experimental and set the channel using `++customize welcomeChannel CHANNEL_ID`, or alternatively, use DM welcoming.

**Comment by TLNiles** [comment]
Alright, so updating to experimental fixed the issue, and now bot is able to send welcoming message. Thanks.
