### ISSUE TITLE
Rule34 Links Broken again

### ISSUE THREAD

**Issue by KekMcGee** [TheSharks/WildBeast#305]
Same issues as here https://github.com/TheSharks/WildBeast/issues/293

**Comment by caf203** [comment]
Well, this isn't the first time the api had changed on us. Thanks for the warning, should be fixed soon.

**Comment by Dougley** [comment]
Should be fixed in https://github.com/TheSharks/WildBeast/commit/c3f669cc583a325b0e032df43da292cf31cc5020
