### ISSUE TITLE
cleverbot command status?

### ISSUE THREAD

**Issue by TLNiles** [TheSharks/WildBeast#309]
So, with 4.5.0 from experimental branch being merged with master, cleverbot command is now gone for good? Will it be returned to WildBeast functionality or was it causing problems and cleverbot is no longer supported?

**Comment by zaza7** [comment]
The command was only disabled, those who are self hosting are able to remove the `/* ... */` around the command code to enable it once again.

**Comment by TLNiles** [comment]
Hmmm. Even after enabling the command again, now it doesn't seem to work.
In Discord, bot returns this kind of error:
An error occurred while trying to process this command, you should let the bot author know. 
ReferenceError: cleverbot is not defined
If it supposed to be working - what would be the cause? I have API user and key set up in config, so that's clearly not it, right?

**Comment by zaza7** [comment]
At the top of the fun.js file are two lines that are also commented out using `//`. These two forward slashes need to be removed as well.

**Comment by TLNiles** [comment]
Ah, okay. Got it resolved, thanks.
