### ISSUE TITLE
[EXPIRAMENTAL] Error thrown by request command

### ISSUE THREAD

**Issue by ZandercraftGames** [TheSharks/WildBeast#314]
![image](https://user-images.githubusercontent.com/28664144/36337493-aaf8e1e0-1365-11e8-896a-52fd7367d0d9.png)

**Comment by Nenkai** [comment]
This has nothing to do with the `experimental` branch.

Download [youtube-dl](https://yt-dl.org/downloads/2018.02.11/youtube-dl.exe) and place the binary in `node_modules/youtube-dl/bin/` .
