### ISSUE TITLE
[Expiramental] Welcome message isn't working.

### ISSUE THREAD

**Issue by ZandercraftGames** [TheSharks/WildBeast#316]
The welcome message wont work. I even brought back the +customize welcomeChannel command back and still, the command doesnt work. It is set to +customize welcoming channel Plus, it returns this error whenever anyone joins. And before you say: "did you set a welcome message"... Yes... I did.
`error:  TypeError: Cannot read property 'sendMessage' of null
    at datacontrol.customize.reply.then (C:\Users\MyName\Desktop\WildBeast\DougBot.js:266:34)
    at <anonymous>`

**Comment by Dougley** [comment]
We don't support modified versions of WildBeast.
<sub><sup><code>Expiramental</code></sup></sub>
