### ISSUE TITLE
Problem with WildBot

### ISSUE THREAD

**Issue by riadxxx** [TheSharks/WildBeast#318]
Your bot - WildBot works not correct, everyone who have just 2nd lvl can use commands ++leave-voice,change volume and use pause, what can be really annoying. Please fix it.

**Comment by linuswillner** [comment]
That's an intentional restriction. "Administrative" music commands are purposefully restricted to level 2, as they have more authority than the rest (Which are restricted to level 1).

**Comment by linuswillner** [comment]
Closing this as it does not pertain to WildBeast directly. For further discussion and/or requests, please refer to https://discord.gg/wildbot.

**Comment by riadxxx** [comment]
Please reopen my issue i did mistake in writing that.

**Comment by linuswillner** [comment]
If you have a different issue, feel free to file a new one as long as it pertains to WildBeast as software. If it concerns WildBot or any other service we provide, please refer to the link I sent earlier.
