### ISSUE TITLE
.env command configuration issues

### ISSUE THREAD

**Issue by lazeraman** [TheSharks/WildBeast#325]
The command that require the .env configurations are not working for me. I doubt I configured it correctly since the linked page does not really help with how to set up the file but I did as follows:

IMGFLIP_USERNAME="xxxx@xxx.com"
IMGFLIP_PASSWORD="xxxxxxx"
IMGUR_KEY="xxxxxx"
TWITCH_ID="xxxxxx"
WILDBEAST_VOICE_PERSIST=true

Errors for each command:

CMD: randommeme by XXXX in test
ERROR: REST call failed: Error: Forbidden

CMD: twitch by XXXX in test
ERROR: TypeError [ERR_MISSING_ARGS]: The "value" argument must be specified
    at validateHeader (_http_outgoing.js:501:11)
    at ClientRequest.setHeader (_http_outgoing.js:510:3)
    at Request.request (/opt/wildbeast/node_modules/superagent/lib/node/index.js:660:11)
    at Request.end (/opt/wildbeast/node_modules/superagent/lib/node/index.js:764:8)
    at Object.fn (/opt/wildbeast/src/commands/twitch.js:17:10)
    at Object.module.exports [as messageCreate] (/opt/wildbeast/src/events/messageCreate.js:66:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)

Can someone tell me the correct way to setup the .env file?

**Comment by zaza7** [comment]
you do not need the quote marks around the values for the fields.

**Comment by lazeraman** [comment]
removed the quotes, but it seems I am still having the same issues. Can an example be uploaded?

**Comment by linuswillner** [comment]
I have a sneaking suspicion this is actually related to how Docker handles environment variables... Since the .env file is created after the image is composed, it won’t work. This needs further investigation.

CC @Dougley

**Comment by linuswillner** [comment]
A temporary remedy is manually adding the environment variables to the docker-compose.yml file in the same manner that the core variables are defined, and then re-composing the image. Suggest you try that.

**Comment by Dougley** [comment]
Due to how docker works, you'd need to declare to docker-compose that you want to use a dotenv file.
We plan on adding this ourselves later, but for now you can workaround this by adding `env_file: .env` to the wildbeast container configuration.

**Comment by linuswillner** [comment]
@lazeraman Documentation and Docker images have now been updated to reflect the issues you raised here. However, the changes only happened in the `latest` image, so we suggest you remove existing containers and images, then re-compose the images under the new configuration procedure (https://docs.thesharks.xyz/install_linux/#setup).

Thank you for reporting this!

**Comment by lazeraman** [comment]
Thanks!
