### ISSUE TITLE
Need to know how to install 4.5.0...

### ISSUE THREAD

**Issue by AlexanderTheCrafter** [TheSharks/WildBeast#333]
Hey. Thanks @Dougley for sending me the WildBeast archive for experimental version 4.5.0. All I need now are the install instructions. I checked WildBeast Docs's repo but all I could find was install instructions for V6.

**Comment by linuswillner** [comment]
We do not host installation instructions for v4 anymore because that version is not supported anymore. However, the WildBeastDocs repository has archives of all installation instructions pre-v6, so you should browse the repo at a point prior to the v6 documentation release.

**Comment by AlexanderTheCrafter** [comment]
@linuswillner Hmm... cause I dont see any releases or tags. How am I supposed to? Just browse to a previous commit?

**Comment by AlexanderTheCrafter** [comment]
May I ask when V6 came out?

**Comment by AlexanderTheCrafter** [comment]
Also.... already just figured that one out... But has WildBeast Docs's web-page on that repo been updated since 4.4.0?

**Comment by Dougley** [comment]
The legacy documentation for version 4.x can be found at https://thesharks.github.io/WildBeastDocs/

**Comment by AlexanderTheCrafter** [comment]
I do hope to upgrade to v6 Dougley... Just not now. I like to know that there has been enough time for all the bugs to be worked out before I use the software... Sort-of like when Windows 8 came out. That thing was a mess. Im just waiting a little while until its a little more stable. V6 seemed a little like it was rushed to the "market", as you did completely skip V5.
