### ISSUE TITLE
Decoupling from Docker

### ISSUE THREAD

**Issue by aburrobb** [TheSharks/WildBeast#334]
Hello,
I installed the bot on an Ubuntu 16.04 and worked perfectly.
trying to running it from source (decoupling from Docker), but the bot fails at "npm run dbcreate" and "npm start".

Output of "npm run dbcreate":

aburrobb@ubuntu:~/WildBeast$ npm run dbcreate

> wildbeast@6.0.0 dbcreate /home/aburrobb/WildBeast
> node src/internal/db-init.js

/home/aburrobb/WildBeast/src/internal/db-init.js:18
driver.listDatabases().then(async databases => {
                            ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

npm ERR! Linux 4.4.0-128-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dbcreate"
npm ERR! node v6.14.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! wildbeast@6.0.0 dbcreate: `node src/internal/db-init.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wildbeast@6.0.0 dbcreate script 'node src/internal/db-init.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wildbeast package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node src/internal/db-init.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wildbeast
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wildbeast
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/aburrobb/WildBeast/npm-debug.log

*******************************************************************************

Output of "npm start":

aburrobb@ubuntu:~/WildBeast$ npm start

> wildbeast@6.0.0 start /home/aburrobb/WildBeast
> node index.js

/home/aburrobb/WildBeast/src/internal/i18n.js:17
  send: async (key, channel, opts) => {
              ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/aburrobb/WildBeast/index.js:3:15)

npm ERR! Linux 4.4.0-128-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.14.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! wildbeast@6.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wildbeast@6.0.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wildbeast package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wildbeast
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wildbeast
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/aburrobb/WildBeast/npm-debug.log

******************************************************************************

The output of "npm i":

aburrobb@ubuntu:~/WildBeast$ npm i
wildbeast@6.0.0 /home/aburrobb/WildBeast
├─┬ @thesharks/jagtag-js@1.0.3
│ ├── expr-eval@1.2.1
│ ├── levenshtein-lite@1.0.9
│ ├── lokijs@1.5.5
│ ├── require-directory@2.1.1
│ └── xregexp@4.1.1  (git://github.com/thesharks/xregexp.git#ba504a7726a0e098fb5                                                                                                                                                             81d7513fc4095794b1744)
├─┬ arangojs@6.3.0
│ ├── es6-error@4.1.1
│ ├── linkedlist@1.0.1
│ ├─┬ multi-part@2.0.0
│ │ └─┬ mime-kind@2.0.2
│ │   └── file-type@4.4.0
│ ├── utf8-length@0.0.1
│ └─┬ xhr@2.5.0
│   ├─┬ global@4.3.2
│   │ ├─┬ min-document@2.19.0
│   │ │ └── dom-walk@0.1.1
│   │ └── process@0.5.2
│   ├── is-function@1.0.1
│   ├─┬ parse-headers@2.0.1
│   │ ├─┬ for-each@0.3.3
│   │ │ └── is-callable@1.1.3
│   │ └── trim@0.0.1
│   └── xtend@4.0.1
├─┬ chalk@2.4.1
│ ├─┬ ansi-styles@3.2.1
│ │ └─┬ color-convert@1.9.2
│ │   └── color-name@1.1.1
│ ├── escape-string-regexp@1.0.5
│ └─┬ supports-color@5.4.0
│   └── has-flag@3.0.0
├── dotenv@4.0.0
├─┬ elasticsearch@14.2.2
│ ├─┬ agentkeepalive@3.4.1
│ │ └─┬ humanize-ms@1.2.1
│ │   └── ms@2.1.1
│ ├─┬ chalk@1.1.3
│ │ ├── ansi-styles@2.2.1
│ │ ├─┬ has-ansi@2.0.0
│ │ │ └── ansi-regex@2.1.1
│ │ ├── strip-ansi@3.0.1
│ │ └── supports-color@2.0.0
│ ├── lodash@2.4.2
│ ├── lodash.get@4.4.2
│ ├── lodash.isempty@4.4.0
│ └── lodash.trimend@4.5.1
├─┬ eris@0.8.6
│ ├── opusscript@0.0.4
│ ├── tweetnacl@1.0.0
│ └── ws@5.2.1
├─┬ eris-lavalink@1.0.2
│ ├─┬ eris@0.8.6  (git://github.com/abalabahaha/eris.git#b7444038963f943496ab452                                                                                                                                                             44a990eaec207f46f)
│ │ └── ws@5.2.1
│ └─┬ ws@3.3.3
│   └── ultron@1.1.1
├─┬ eslint@4.19.1
│ ├─┬ ajv@5.5.2
│ │ ├── co@4.6.0
│ │ ├── fast-deep-equal@1.1.0
│ │ ├── fast-json-stable-stringify@2.0.0
│ │ └── json-schema-traverse@0.3.1
│ ├─┬ babel-code-frame@6.26.0
│ │ ├─┬ chalk@1.1.3
│ │ │ ├── ansi-styles@2.2.1
│ │ │ └── supports-color@2.0.0
│ │ └── js-tokens@3.0.2
│ ├─┬ concat-stream@1.6.2
│ │ ├── buffer-from@1.1.0
│ │ ├── inherits@2.0.3
│ │ └── typedarray@0.0.6
│ ├─┬ cross-spawn@5.1.0
│ │ ├─┬ lru-cache@4.1.3
│ │ │ ├── pseudomap@1.0.2
│ │ │ └── yallist@2.1.2
│ │ ├─┬ shebang-command@1.2.0
│ │ │ └── shebang-regex@1.0.0
│ │ └─┬ which@1.3.1
│ │   └── isexe@2.0.0
│ ├─┬ debug@3.1.0
│ │ └── ms@2.0.0
│ ├── doctrine@2.1.0
│ ├─┬ eslint-scope@3.7.1
│ │ ├── esrecurse@4.2.1
│ │ └── estraverse@4.2.0
│ ├── eslint-visitor-keys@1.0.0
│ ├─┬ espree@3.5.4
│ │ ├── acorn@5.7.1
│ │ └─┬ acorn-jsx@3.0.1
│ │   └── acorn@3.3.0
│ ├── esquery@1.0.1
│ ├── esutils@2.0.2
│ ├─┬ file-entry-cache@2.0.0
│ │ ├─┬ flat-cache@1.3.0
│ │ │ ├── circular-json@0.3.3
│ │ │ ├─┬ del@2.2.2
│ │ │ │ ├─┬ globby@5.0.0
│ │ │ │ │ ├─┬ array-union@1.0.2
│ │ │ │ │ │ └── array-uniq@1.0.3
│ │ │ │ │ └── arrify@1.0.1
│ │ │ │ ├── is-path-cwd@1.0.0
│ │ │ │ ├─┬ is-path-in-cwd@1.0.1
│ │ │ │ │ └── is-path-inside@1.0.1
│ │ │ │ ├── pify@2.3.0
│ │ │ │ ├─┬ pinkie-promise@2.0.1
│ │ │ │ │ └── pinkie@2.0.4
│ │ │ │ └── rimraf@2.6.2
│ │ │ └── write@0.2.1
│ │ └── object-assign@4.1.1
│ ├── functional-red-black-tree@1.0.1
│ ├─┬ glob@7.1.2
│ │ ├── fs.realpath@1.0.0
│ │ ├─┬ inflight@1.0.6
│ │ │ └── wrappy@1.0.2
│ │ ├── once@1.4.0
│ │ └── path-is-absolute@1.0.1
│ ├── globals@11.7.0
│ ├── ignore@3.3.10
│ ├── imurmurhash@0.1.4
│ ├─┬ inquirer@3.3.0
│ │ ├── ansi-escapes@3.1.0
│ │ ├─┬ cli-cursor@2.1.0
│ │ │ └─┬ restore-cursor@2.0.0
│ │ │   ├─┬ onetime@2.0.1
│ │ │   │ └── mimic-fn@1.2.0
│ │ │   └── signal-exit@3.0.2
│ │ ├── cli-width@2.2.0
│ │ ├─┬ external-editor@2.2.0
│ │ │ ├── chardet@0.4.2
│ │ │ ├─┬ iconv-lite@0.4.23
│ │ │ │ └── safer-buffer@2.1.2
│ │ │ └─┬ tmp@0.0.33
│ │ │   └── os-tmpdir@1.0.2
│ │ ├── figures@2.0.0
│ │ ├── lodash@4.17.10
│ │ ├── mute-stream@0.0.7
│ │ ├─┬ run-async@2.3.0
│ │ │ └── is-promise@2.1.0
│ │ ├── rx-lite@4.0.8
│ │ ├── rx-lite-aggregates@4.0.8
│ │ ├─┬ string-width@2.1.1
│ │ │ ├── is-fullwidth-code-point@2.0.0
│ │ │ └─┬ strip-ansi@4.0.0
│ │ │   └── ansi-regex@3.0.0
│ │ ├─┬ strip-ansi@4.0.0
│ │ │ └── ansi-regex@3.0.0
│ │ └── through@2.3.8
│ ├── is-resolvable@1.1.0
│ ├─┬ js-yaml@3.12.0
│ │ ├─┬ argparse@1.0.10
│ │ │ └── sprintf-js@1.0.3
│ │ └── esprima@4.0.0
│ ├── json-stable-stringify-without-jsonify@1.0.1
│ ├─┬ levn@0.3.0
│ │ ├── prelude-ls@1.1.2
│ │ └── type-check@0.3.2
│ ├── lodash@4.17.10
│ ├─┬ minimatch@3.0.4
│ │ └─┬ brace-expansion@1.1.11
│ │   ├── balanced-match@1.0.0
│ │   └── concat-map@0.0.1
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├── natural-compare@1.4.0
│ ├─┬ optionator@0.8.2
│ │ ├── deep-is@0.1.3
│ │ ├── fast-levenshtein@2.0.6
│ │ └── wordwrap@1.0.0
│ ├── path-is-inside@1.0.2
│ ├── pluralize@7.0.0
│ ├── progress@2.0.0
│ ├── regexpp@1.1.0
│ ├─┬ require-uncached@1.0.3
│ │ ├─┬ caller-path@0.1.0
│ │ │ └── callsites@0.2.0
│ │ └── resolve-from@1.0.1
│ ├── semver@5.5.0
│ ├─┬ strip-ansi@4.0.0
│ │ └── ansi-regex@3.0.0
│ ├── strip-json-comments@2.0.1
│ ├─┬ table@4.0.2
│ │ ├── ajv-keywords@2.1.1
│ │ ├── lodash@4.17.10
│ │ └── slice-ansi@1.0.0
│ └── text-table@0.2.0
├── eslint-config-standard@11.0.0
├─┬ eslint-plugin-import@2.13.0
│ ├── contains-path@0.1.0
│ ├─┬ debug@2.6.9
│ │ └── ms@2.0.0
│ ├─┬ doctrine@1.5.0
│ │ └── isarray@1.0.0
│ ├─┬ eslint-import-resolver-node@0.3.2
│ │ └─┬ debug@2.6.9
│ │   └── ms@2.0.0
│ ├─┬ eslint-module-utils@2.2.0
│ │ ├─┬ debug@2.6.9
│ │ │ └── ms@2.0.0
│ │ └─┬ pkg-dir@1.0.0
│ │   └─┬ find-up@1.1.2
│ │     └── path-exists@2.1.0
│ ├─┬ has@1.0.3
│ │ └── function-bind@1.1.1
│ ├── lodash@4.17.10
│ ├─┬ read-pkg-up@2.0.0
│ │ ├─┬ find-up@2.1.0
│ │ │ └─┬ locate-path@2.0.0
│ │ │   ├─┬ p-locate@2.0.0
│ │ │   │ └─┬ p-limit@1.3.0
│ │ │   │   └── p-try@1.0.0
│ │ │   └── path-exists@3.0.0
│ │ └─┬ read-pkg@2.0.0
│ │   ├─┬ load-json-file@2.0.0
│ │   │ └─┬ parse-json@2.2.0
│ │   │   └─┬ error-ex@1.3.2
│ │   │     └── is-arrayish@0.2.1
│ │   ├─┬ normalize-package-data@2.4.0
│ │   │ ├── hosted-git-info@2.6.1
│ │   │ ├── is-builtin-module@1.0.0
│ │   │ └─┬ validate-npm-package-license@3.0.3
│ │   │   ├─┬ spdx-correct@3.0.0
│ │   │   │ └── spdx-license-ids@3.0.0
│ │   │   └─┬ spdx-expression-parse@3.0.0
│ │   │     └── spdx-exceptions@2.1.0
│ │   └── path-type@2.0.0
│ └─┬ resolve@1.8.1
│   └── path-parse@1.0.5
├─┬ eslint-plugin-node@5.2.1
│ └── semver@5.3.0
├── eslint-plugin-promise@3.8.0
├── eslint-plugin-standard@3.1.0
├─┬ fs-extra@6.0.1
│ ├── graceful-fs@4.1.11
│ ├── jsonfile@4.0.0
│ └── universalify@0.1.2
├── hot-shots@5.6.3
├─┬ imgflipper@1.0.1
│ └─┬ request@2.87.0
│   ├── aws-sign2@0.7.0
│   ├── aws4@1.7.0
│   ├── caseless@0.12.0
│   ├─┬ combined-stream@1.0.6
│   │ └── delayed-stream@1.0.0
│   ├── forever-agent@0.6.1
│   ├─┬ har-validator@5.0.3
│   │ └── har-schema@2.0.0
│   ├─┬ http-signature@1.2.0
│   │ ├── assert-plus@1.0.0
│   │ ├─┬ jsprim@1.4.1
│   │ │ ├── extsprintf@1.3.0
│   │ │ ├── json-schema@0.2.3
│   │ │ └── verror@1.10.0
│   │ └─┬ sshpk@1.14.2
│   │   ├── asn1@0.2.3
│   │   ├─┬ bcrypt-pbkdf@1.0.2
│   │   │ └── tweetnacl@0.14.5
│   │   ├── dashdash@1.14.1
│   │   ├── ecc-jsbn@0.1.1
│   │   ├── getpass@0.1.7
│   │   ├── jsbn@0.1.1
│   │   └── tweetnacl@0.14.5
│   ├── is-typedarray@1.0.0
│   ├── isstream@0.1.2
│   ├── json-stringify-safe@5.0.1
│   ├─┬ mime-types@2.1.18
│   │ └── mime-db@1.33.0
│   ├── oauth-sign@0.8.2
│   ├── performance-now@2.1.0
│   ├─┬ tough-cookie@2.3.4
│   │ └── punycode@1.4.1
│   ├── tunnel-agent@0.6.0
│   └── uuid@3.3.2
├─┬ mocha@5.2.0
│ ├── browser-stdout@1.3.1
│ ├── commander@2.15.1
│ ├── diff@3.5.0
│ ├── growl@1.10.5
│ └── he@1.1.1
├── moment@2.22.2
├─┬ raven@2.6.3
│ ├── cookie@0.3.1
│ ├─┬ md5@2.2.1
│ │ ├── charenc@0.0.2
│ │ ├── crypt@0.0.2
│ │ └── is-buffer@1.1.6
│ ├── stack-trace@0.0.10
│ ├── timed-out@4.0.1
│ └── uuid@3.0.0
├─┬ standard@10.0.3
│ ├─┬ UNMET PEER DEPENDENCY eslint@3.19.0
│ │ ├─┬ chalk@1.1.3
│ │ │ ├── ansi-styles@2.2.1
│ │ │ └── supports-color@2.0.0
│ │ ├─┬ debug@2.6.9
│ │ │ └── ms@2.0.0
│ │ ├─┬ escope@3.6.0
│ │ │ ├─┬ es6-map@0.1.5
│ │ │ │ ├── d@1.0.0
│ │ │ │ ├─┬ es5-ext@0.10.45
│ │ │ │ │ └── next-tick@1.0.0
│ │ │ │ ├── es6-iterator@2.0.3
│ │ │ │ ├── es6-set@0.1.5
│ │ │ │ ├── es6-symbol@3.1.1
│ │ │ │ └── event-emitter@0.3.5
│ │ │ └── es6-weak-map@2.0.2
│ │ ├── globals@9.18.0
│ │ ├─┬ inquirer@0.12.0
│ │ │ ├── ansi-escapes@1.4.0
│ │ │ ├─┬ cli-cursor@1.0.2
│ │ │ │ └─┬ restore-cursor@1.0.1
│ │ │ │   ├── exit-hook@1.1.1
│ │ │ │   └── onetime@1.1.0
│ │ │ ├── figures@1.7.0
│ │ │ ├─┬ readline2@1.0.1
│ │ │ │ ├── code-point-at@1.1.0
│ │ │ │ ├─┬ is-fullwidth-code-point@1.0.0
│ │ │ │ │ └── number-is-nan@1.0.1
│ │ │ │ └── mute-stream@0.0.5
│ │ │ ├── run-async@0.1.0
│ │ │ ├── rx-lite@3.1.2
│ │ │ └─┬ string-width@1.0.2
│ │ │   └── is-fullwidth-code-point@1.0.0
│ │ ├─┬ is-my-json-valid@2.17.2
│ │ │ ├── generate-function@2.0.0
│ │ │ ├─┬ generate-object-property@1.2.0
│ │ │ │ └── is-property@1.0.2
│ │ │ ├── is-my-ip-valid@1.0.0
│ │ │ └── jsonpointer@4.0.1
│ │ ├─┬ json-stable-stringify@1.0.1
│ │ │ └── jsonify@0.0.0
│ │ ├── lodash@4.17.10
│ │ ├── pluralize@1.2.1
│ │ ├── progress@1.1.8
│ │ ├─┬ shelljs@0.7.8
│ │ │ ├── interpret@1.1.0
│ │ │ └── rechoir@0.6.2
│ │ ├── strip-bom@3.0.0
│ │ ├─┬ table@3.8.3
│ │ │ ├── ajv@4.11.8
│ │ │ ├── ajv-keywords@1.5.1
│ │ │ ├── slice-ansi@0.0.4
│ │ │ └─┬ string-width@2.1.1
│ │ │   ├── is-fullwidth-code-point@2.0.0
│ │ │   └─┬ strip-ansi@4.0.0
│ │ │     └── ansi-regex@3.0.0
│ │ └─┬ user-home@2.0.0
│ │   └── os-homedir@1.0.2
│ ├── eslint-config-standard@10.2.1
│ ├── eslint-config-standard-jsx@4.0.2
│ ├─┬ eslint-plugin-import@2.2.0
│ │ ├── builtin-modules@1.1.1
│ │ ├── doctrine@1.5.0
│ │ ├── eslint-import-resolver-node@0.2.3
│ │ ├── lodash.cond@4.5.2
│ │ └── pkg-up@1.0.0
│ ├─┬ eslint-plugin-node@4.2.3
│ │ └── semver@5.3.0
│ ├── eslint-plugin-promise@3.5.0
│ ├─┬ eslint-plugin-react@6.10.3
│ │ ├─┬ array.prototype.find@2.0.4
│ │ │ ├─┬ define-properties@1.1.2
│ │ │ │ └── foreach@2.0.5
│ │ │ └─┬ es-abstract@1.12.0
│ │ │   ├─┬ es-to-primitive@1.1.1
│ │ │   │ ├── is-date-object@1.0.1
│ │ │   │ └── is-symbol@1.0.1
│ │ │   └── is-regex@1.0.4
│ │ ├── doctrine@1.5.0
│ │ ├── jsx-ast-utils@1.4.1
│ │ └─┬ object.assign@4.1.0
│ │   ├── has-symbols@1.0.0
│ │   └── object-keys@1.0.12
│ ├── eslint-plugin-standard@3.0.1
│ └─┬ standard-engine@7.0.0
│   ├─┬ deglob@2.1.1
│   │ ├── find-root@1.1.0
│   │ ├─┬ pkg-config@1.1.1
│   │ │ └── debug-log@1.0.1
│   │ ├── run-parallel@1.1.9
│   │ └── uniq@1.0.1
│   ├── get-stdin@5.0.1
│   ├── minimist@1.2.0
│   └─┬ pkg-conf@2.1.0
│     ├── find-up@2.1.0
│     └─┬ load-json-file@4.0.0
│       ├─┬ parse-json@4.0.0
│       │ └── json-parse-better-errors@1.0.2
│       └── pify@3.0.0
├─┬ superagent@3.8.3
│ ├── component-emitter@1.2.1
│ ├── cookiejar@2.1.2
│ ├── extend@3.0.1
│ ├─┬ form-data@2.3.2
│ │ └── asynckit@0.4.0
│ ├── formidable@1.2.1
│ ├── methods@1.1.2
│ ├── mime@1.6.0
│ ├── qs@6.5.2
│ └─┬ readable-stream@2.3.6
│   ├── core-util-is@1.0.2
│   ├── process-nextick-args@2.0.0
│   ├── string_decoder@1.1.1
│   └── util-deprecate@1.0.2
├─┬ uglify-es@3.3.9
│ ├── commander@2.13.0
│ └── source-map@0.6.1
├─┬ ws@4.1.0
│ ├── async-limiter@1.0.0
│ └── safe-buffer@5.1.2
└─┬ xml-js@1.6.4
  └── sax@1.2.4

npm WARN eslint-plugin-react@6.10.3 requires a peer of eslint@^2.0.0 || ^3.0.0 b                                                                                                                                                             ut none was installed.

**************************************************************************

Content of npm-debug.log"

aburrobb@ubuntu:~/WildBeast$ cat /home/aburrobb/WildBeast/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dbcreate' ]
2 info using npm@3.10.10
3 info using node@v6.14.3
4 verbose run-script [ 'predbcreate', 'dbcreate', 'postdbcreate' ]
5 info lifecycle wildbeast@6.0.0~predbcreate: wildbeast@6.0.0
6 silly lifecycle wildbeast@6.0.0~predbcreate: no script for predbcreate, continuing
7 info lifecycle wildbeast@6.0.0~dbcreate: wildbeast@6.0.0
8 verbose lifecycle wildbeast@6.0.0~dbcreate: unsafe-perm in lifecycle true
9 verbose lifecycle wildbeast@6.0.0~dbcreate: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/aburrobb/WildBeast/node_modules/.bin:/home/aburrobb/bin:/home/aburrobb/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle wildbeast@6.0.0~dbcreate: CWD: /home/aburrobb/WildBeast
11 silly lifecycle wildbeast@6.0.0~dbcreate: Args: [ '-c', 'node src/internal/db-init.js' ]
12 silly lifecycle wildbeast@6.0.0~dbcreate: Returned: code: 1  signal: null
13 info lifecycle wildbeast@6.0.0~dbcreate: Failed to exec dbcreate script
14 verbose stack Error: wildbeast@6.0.0 dbcreate: `node src/internal/db-init.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid wildbeast@6.0.0
16 verbose cwd /home/aburrobb/WildBeast
17 error Linux 4.4.0-128-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "dbcreate"
19 error node v6.14.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error wildbeast@6.0.0 dbcreate: `node src/internal/db-init.js`
22 error Exit status 1
23 error Failed at the wildbeast@6.0.0 dbcreate script 'node src/internal/db-init.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the wildbeast package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node src/internal/db-init.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs wildbeast
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls wildbeast
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

************************************************************************

Please advice.
Thanks and Regards.

**Comment by linuswillner** [comment]
Your Node.js version is outdated. That’s an omission we’ve made in the docs, I should add that.

You need to have Node.js 8 or higher installed.
