### ISSUE TITLE
Wont Start.

### ISSUE THREAD

**Issue by AlexanderTheCrafter** [TheSharks/WildBeast#339]
I completely followed everything at: https://thesharks.github.io/WildBeastDocs/install_linux/ to Install version 4.4.0 except for the fact that I used the .zip source code instead of the git clone command. And after running `npm install` the bot wont start. This is after I already had the bot running perfectly, ran `npm update` to update everything then had to re-install it because it made the bot have a long error and not start... Now even after reinstalling it perfectly to the letter of what you said in the docs I still get the long error and it wont work... P.S. Im on ubuntu 16.04.

**Comment by AlexanderTheCrafter** [comment]
And I am not running 6.0 or 6.1 because my machine lacks native virtualization support and is 32 bit so it cannot run docker...

**Comment by AlexanderTheCrafter** [comment]
Plus the docker install isnt as easy to customize or as customizable.

**Comment by AlexanderTheCrafter** [comment]
And it doesnt have all the commands from 4.4.0

**Comment by linuswillner** [comment]
WildBeast version 4 is deprecated and no longer supported. The old code is not maintained and thus there are no guarantees of it working.

We may be able to help you if you post the stack trace, but some issues with that version are not fixable.

**Comment by Dougley** [comment]
Please provide any errors and a screenshot of your console

**Comment by ZandercraftGames** [comment]
@AlexanderTheCrafter I know that you have a 64-bit game server running... Why not use it on that?

**Comment by ZandercraftGames** [comment]
P.S. @Dougley Im planning on running the official 1.6 build... Will DockerToolbox suffice?

**Comment by ZandercraftGames** [comment]
Because my newest PC is Home Edition and 
![image](https://user-images.githubusercontent.com/28664144/45254744-2b967580-b34b-11e8-81ac-0521ee5acec5.png)

**Comment by ZandercraftGames** [comment]
It seems to have the same utilities...

**Comment by linuswillner** [comment]
@ZandercraftGames Please keep discussion unrelated to the issue at hand out of this thread. You may raise a separate issue or contact us for these queries via other means.

**Comment by ZandercraftGames** [comment]
@linuswillner Kind of hard to when you banned me from your Discord...

**Comment by linuswillner** [comment]
@ZandercraftGames Oh right, I forgot. You can raise a separate issue on the matter in this repository.

**Comment by ZandercraftGames** [comment]
How could you ever forget me? :( xD

**Comment by AlexanderTheCrafter** [comment]
Hmm... @ZandercraftGames Maybe I will... I am just afraid it might lag some of the other programs...
@Dougley How resource intensive is it?

**Comment by linuswillner** [comment]
”It?”

**Comment by ZandercraftGames** [comment]
@linuswillner I'm pretty sure he is referring to the WildBeast Process combined with the DB and Docker.

**Comment by ZandercraftGames** [comment]
But uhh yeh... Rethinkdb was probably more resource intensive...

**Comment by linuswillner** [comment]
Addendum to my previous, you are likely not looking at memory consumption over 1 GB. This is a rough estimate as we haven’t tried WB in very low-spec environments, v4 did work on just half a gig but I feel that’s a bit of a close shave in any case. 1 GB consumption altogether should be a safe estimate.

**Comment by ZandercraftGames** [comment]
My old WildBeast server had 2 GB and it was constantly going into swap space...

**Comment by ZandercraftGames** [comment]
However if you are running it to just one server... It shouldn't. My case was only because it was in at least 3 voice channels or more at any given time.

**Comment by ZandercraftGames** [comment]
P.S. Enjoy migration... Its fun... :D

**Comment by ZandercraftGames** [comment]
He upgraded. @Dougley You can close this issue... Hes my friend BTW.
