### ISSUE TITLE
Disable Porn

### ISSUE THREAD

**Issue by ZandercraftGames** [TheSharks/WildBeast#341]
I deleted the .js files for booru rule34 and e621... but they are still listed as commands in the help command. How do I remove these commands?

**Comment by ZandercraftGames** [comment]
It only says the decoupling method for linux... How do I decouple in a windows environment?

**Comment by linuswillner** [comment]
The decoupling documentatation provides instructions for both Windows and Linux.
![Docs](https://i.linuswillner.me/nwLZ4GP.png)

**Comment by ZandercraftGames** [comment]
So I want to do the reconfiguring section then the windows section... And then whenever I click start in Kitematic it will start from source code?

**Comment by ZandercraftGames** [comment]
Or then how to I start it from source code if I delete the wildbeast install and wildbeast wildbeast images?

**Comment by Dougley** [comment]
![](https://i.imgur.com/MNa8bSH.jpg)

**Comment by linuswillner** [comment]
Your questions are adequately answered by the decoupling guide. It instructs the removal of the containers and starting in source mode.

**Comment by ZandercraftGames** [comment]
But how do you start in source mode where does it day?

**Comment by ZandercraftGames** [comment]
*say

**Comment by linuswillner** [comment]
See the **Installing dependencies and starting** section.

**Comment by ZandercraftGames** [comment]
Oh ok... I see now

**Comment by ZandercraftGames** [comment]
Anyways... I know that the bot sometimes crashes when it hits an error... How do I prevent this... cause I know it doesnt crash when in docker.

**Comment by ZandercraftGames** [comment]
But only crashes when running from source

**Comment by linuswillner** [comment]
That should be a fairly rare occurrence, but it's still expected behaviour. If there is an uncaught exception, the process exits. You can't really prevent this behaviour, but you can use systems to mitigate it. Programs like PM2 (https://pm2.keymetrics.io) have the ability to automatically restart the process when it exits.

**Comment by ZandercraftGames** [comment]
Does PM2 work on Windows?

**Comment by ZandercraftGames** [comment]
Because I remember 4.5.0 crashed soooooo often with errors about voice.js

**Comment by linuswillner** [comment]
PM2 is not intended to be run on Windows per se, but it will work in most circumstances. I recommend looking up guides online on the quirks associated with using Windows for this task. Otherwise it is just a Node.js application which is inherently cross-platform.

WildBeast v6 is much more stable in terms of errors. This was a more frequent occurrence with previous versions, but due to improvements in code quality it should be an increasingly infrequent issue nowadays.

**Comment by linuswillner** [comment]
The port values are editable. The only thing you cannot edit is the IP address, which is either `localhost` or an IPv4 address depending on whether you're using Docker Toolbox or not, the latter being used in this case.

**Comment by ZandercraftGames** [comment]
@linuswillner ?

**Comment by ZandercraftGames** [comment]
So what do I do with it not being localhost?

**Comment by ZandercraftGames** [comment]
Will it function the same still?

**Comment by linuswillner** [comment]
That's expected behaviour, like I just said. This due to how Docker Toolbox handles networking. The only difference is that you use that IP address as opposed to `localhost` when reconfiguring the environment, as described in the guide.

**Comment by ZandercraftGames** [comment]
But the Docker Port jsnt configurable... only the other one...

**Comment by ZandercraftGames** [comment]
So then how would I set the docker port too?

**Comment by linuswillner** [comment]
That's a non-issue. It's most likely already pointing to the correct port in Docker.

**Comment by ZandercraftGames** [comment]
So I would set the LAVA_NODES thing to the ip instead of localhost and the arango URI to that ip too in .env? And then it will work?

**Comment by linuswillner** [comment]
Yes.

**Comment by ZandercraftGames** [comment]
Also what about elastic search?

**Comment by Dougley** [comment]
Locking this issue, GitHub issues are not for extended support and it's getting extremely off topic from the original question

**Comment by linuswillner** [comment]
Your queries should be adequately answered by the documentation from here on out.
