### ISSUE TITLE
Music Error

### ISSUE THREAD

**Issue by ZandercraftGames** [TheSharks/WildBeast#342]
I am running WildBeast, ArrangoDB, and the music thingy with Docker and I get an error about unknown length of undefined when running music commands but no errors when starting the music container or wildbeast container or the DB container.

**Comment by caf203** [comment]
Please provide an error log or the stacktrace.

**Comment by ZandercraftGames** [comment]
`INFO: Beginning startup sequence...
INFO: Scaling known. Total: 1, mine: 0
INFO: Fully up-to-date, nice!
INFO: Fully ready, serving 491 guild(s).
INFO: LavaLink node ws://192.168.99.100:2333 ready.
CMD: join-voice by ZandercraftGamesYT in Zandercraft PE Server | United MCPE/MC Windows 10
ERROR: Error: Error: Not Found
    at resolveTracks (C:\Users\j3zza\Desktop\WildBeast\src\encoders\lavalink.js:58:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
CMD: join-voice by ZandercraftGamesYT in Zandercraft PE Server | United MCPE/MC Windows 10
ERROR: Error: Error: Not Found
    at resolveTracks (C:\Users\j3zza\Desktop\WildBeast\src\encoders\lavalink.js:58:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
CMD: ping by ZandercraftGamesYT in Zandercraft PE Server | United MCPE/MC Windows 10
CMD: join-voice by ZandercraftGamesYT in Zandercraft PE Server | United MCPE/MC Windows 10
CMD: request by ZandercraftGamesYT in Zandercraft PE Server | United MCPE/MC Windows 10
ERROR: Error: Error: Not Found
    at resolveTracks (C:\Users\j3zza\Desktop\WildBeast\src\encoders\lavalink.js:58:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by ZandercraftGames** [comment]
https://pastebin.com/iPn0eepL

**Comment by ZandercraftGames** [comment]
@caf203

**Comment by ZandercraftGames** [comment]
@linuswillner ?

**Comment by ZandercraftGames** [comment]
Hmm... Because it was doing it before I de-coupled it... It gave this same error or a similar one when it was first installed in docker.

**Comment by linuswillner** [comment]
I see. No matter, we are investigating a remedy and will issue a correction when we have a solution.

**Comment by ZandercraftGames** [comment]
Ok. Thanks

**Comment by ZandercraftGames** [comment]
Got a fix yet or no? Hows progress?

**Comment by Dougley** [comment]
Please verify you're running lavalink v3 and not v2

**Comment by ZandercraftGames** [comment]
@Dougley How would I do that?

**Comment by ZandercraftGames** [comment]
`       .   _                  _ _       _    __ _ _
      /\\ | | __ ___   ____ _| (_)_ __ | | __\ \ \ \
     ( ( )| |/ _` \ \ / / _` | | | '_ \| |/ / \ \ \ \
      \\/ | | (_| |\ V / (_| | | | | | |   <   ) ) ) )
       '  |_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\ / / / /
    =========================================/_/_/_/
2018-09-08T21:36:53.301548737Z 
    :: Lavalink    ::       
    :: Spring Boot ::        (v2.0.0.RELEASE)
2018-09-08T21:36:53.301712681Z `

**Comment by Dougley** [comment]
Your issue is most likely related to you running lavalink v2. If you're using Docker, you can use the new compose file at https://github.com/TheSharks/WildBeast/blob/9688e75c91edc440d797576e9e3fdaa081413166/docker-compose.yml, otherwise reinstall lavalink yourself.

**Comment by ZandercraftGames** [comment]
@Dougley You have not yet replied how to check what lavalink version it is... And if it is the wrong lavalink version it would be because of improper setup and documentation on your part as I installed it following your documentation to the letter.

**Comment by ZandercraftGames** [comment]
This issue was not complete and therefore it is bad practice to close the issue before the it has been sorted out.

**Comment by ZandercraftGames** [comment]
@Dougley You should not be too quick to that close button.

**Comment by Dougley** [comment]
I suggest you change your tone of voice, you've already been banned from our support Discord for the same degree of hostility shown here. We're not tech support, use Google to find out what you need for basic stuff. Besides, this is my repository, so who are you to call me out on "bad practices"?

**Comment by linuswillner** [comment]
Documentation corrections are pending in #344, there are still some kinks to iron out in this PR. When it's merged, corrected decoupling documentation will be deployed.

As that PR mentions, what you are experiencing is an issue of partially our doing in addition to using the wrong Lavalink version. Please wait for the corrected documentation to receive additional instructions.
