### ISSUE TITLE
RandomMeme Issue

### ISSUE THREAD

**Issue by ZandercraftGames** [TheSharks/WildBeast#343]
`CMD: randommeme by ZandercraftGamesYT in DM
ERROR: REST call failed: Error: Forbidden`
Running randommeme command fails.

**Comment by caf203** [comment]
You need an Imgur API key to use randommeme. Add it to your .env file.
![image](https://user-images.githubusercontent.com/20953919/45271362-6516d000-b474-11e8-9d59-b78b3d0ee72d.png)

**Comment by ZandercraftGames** [comment]
But I already have one @caf203 and I already put one into the config.

**Comment by caf203** [comment]
Make sure it's a valid key.
