### ISSUE TITLE
Welcome Messages

### ISSUE THREAD

**Issue by ZandercraftGames** [TheSharks/WildBeast#355]
I am able to enable welcome messages for dms or a channel but the `+settings welcomeMessage <message here>` command does not work. It says: "You cannot edit that"
From what I understand, this was an issue in 4.5.0 too... however I thought that you guys re-wrote the bot... Why would this issue stay?

**Comment by caf203** [comment]
Latest commit to experimental fixes this. Go ahead and update.

**Comment by GHzGangster** [comment]
This doesn't seem to be completely fixed.

I was able to change the setting, but it didn't affect the welcome message.
I tweaked src/events/guildMemberAdd.js to use data.welcomemessage instead of data.welcomeMessage instead, and it works as expected.

I might make try making a pull request soon.

**Comment by Dougley** [comment]
Upon investigation it seems this is a typo within the whitelist for src/commands/settings.js, welcomeMessage with uppercase is intended to be correct

**Comment by Dougley** [comment]
^This commit should fix this issue
