### ISSUE TITLE
Random Meme returns error.

### ISSUE THREAD

**Issue by ZandercraftGames** [TheSharks/WildBeast#357]
The randommeme command returns this error: `The API failed to respond or returned unusable data, please try again later.`. I have tried everything, from changing callback types to making new apps. Nothing works. And yes I am using the cliend id and not the secret.

**Comment by ZandercraftGames** [comment]
Console error: `ERROR: REST call failed: Error: Forbidden`

**Comment by linuswillner** [comment]
Is the IMGUR_API_KEY environment variable set and correct?

**Comment by ZandercraftGames** [comment]
Yes it is @linuswillner

**Comment by linuswillner** [comment]
Works just fine when testing it on an out of the box instance. You may have an invalid API key. In any case, the issue is related to WildBeast.
