### ISSUE TITLE
Connection Reset By Peer

### ISSUE THREAD

**Issue by ZandercraftGames** [TheSharks/WildBeast#379]
WildBeast crashes when it gets the error: connection reset by peer. Why does it not work like the old WildBeast where it keeps trying to reconnect until it gets a connection? Why does it crash?

**Comment by ZandercraftGames** [comment]
I will close this if its not an issue that you plan to fix... If thats the case... then just tell me.

**Comment by linuswillner** [comment]
This is basically a case of “can’t fix” for us as this error is emitted at library level; we don’t have any code in WildBeast to cause this issue, it’s from an external dependency. As such we cannot perform any reconnect attempts or similar manually, nor can we listen to the error event on the socket. All we could do is use `process.on('uncaughtException')`, but it’s a really bad practice and we would still be unable to do anything but restart the application at that stage.
